### ISSUE TITLE
Missing versions

### ISSUE THREAD

**Issue by muffato** [singularityhub/shpc-registry#42]
If you compare the [original](https://github.com/singularityhub/shpc-registry/blob/9ff92fbaa4c449ed8853426566a33206f62c0290/quay.io/biocontainers/samtools/container.yaml) samtools `container.yaml` to the [current](https://github.com/singularityhub/shpc-registry/blob/main/quay.io/biocontainers/samtools/container.yaml) one, you'll notice that it's lost most of its tags !
Is that related to [crane](https://crane.ggcr.dev/ls/quay.io/biocontainers/samtools) returning a subset of the tags ?

**Comment by vsoch** [comment]
We are only returning the first tag discovered in biocontainers, and the tag and digests (for latest) will now be updated in chunks each day of the month, and we do that because there are over 8k containers. It’s against what we originally wanted but is only for the subset of biocontainers anyway, of which we deleted the entire top level root.

**Comment by vsoch** [comment]
These have been fixed - the current matches the previous with the missing aliases.
