### ISSUE TITLE
A first look into some of the automated Biocontainers recipes

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/shpc-registry#86]
Hi @vsoch  @audreystott, 

so today I have checked the list of aliases for the 31x Biocontainers recipes we are currently supported on Setonix, our new supercomputer.
The goal is to check for aliases, with dual purpose:
- Pawsey: to make sure we're providing the needed aliases to researchers
- SHPC hub: to provide feedback on the automated alias generation process

So, out of 31 recipes, only 13 had missing aliases, 10 missing them completely, 3 missing only a few of them.
Notably, out of the other recipes, several identified more useful aliases than I had manually, which is great! :-)

[EDIT] The reference, baseline 31 packages are from SHPC release `0.0.57`, under `registry/quay.io/biocontainers/`: https://github.com/singularityhub/singularity-hpc/tree/0.0.57/registry/quay.io/biocontainers 

[EDIT] I have carried out the check on the latest release of the registry, `2023-02`: https://github.com/singularityhub/shpc-registry/tree/2023-02

Here are the recipes with missing packages: bbmap, bcftools, blast, bwa, fastp, gatk, multiqc, mummer, samtools (only some), spades (only some), star, trinity (only one), velvet

Funny fact: cutadapt and spades have python aliases.. I thought those would have been filtered out.

Now, how do we tackle these in general? I am not sure how to improve the algorithm right now, but .. @vsoch can we provide a CLI to add/edits aliases, and make it so that these are retained, both for final use and eventually also for the algorithm to act better?

Thoughts?

**Comment by vsoch** [comment]
hey @marcodelapierre !

> The 31 packages are from SHPC release 0.0.57, under registry/quay.io/biocontainers

Do you know why you are referencing a version of shpc for the packages before we removed the registry from shpc and added to this repo here? That is a first thing to check - the newer releases of shpc should not have a registry directory, but instead use the remote registry (the repository issue board we are chatting on right now!)

For a spot check, here is the current samtools recipe https://github.com/singularityhub/shpc-registry/commit/e0ed2ea51c4f215df4c76e98477b8e73562a372d. That particular PR Matthieu added back previous tags that were missed by the new parser (since they were older).

>  Funny fact: cutadapt and spades have python aliases.. I thought those would have been filtered out.

https://github.com/singularityhub/shpc-registry/blob/5cc9645465680f9a8ff5fe36119708a25c5cc606/quay.io/biocontainers/cutadapt/container.yaml#L4

The algorithm selects for the aliases under a threshold, and then the next N up to 10. So if python pops up, it just means the container didn't have other unique aliases. I actually think this is ok - someone might want to interact directly with python here. We could explicitly filter out python executables, but this seems like it's more an opinion than a reflection of what a user wants. As soon as we filter out, someone might want them back.

> Now, how do we tackle these in general? I am not sure how to improve the algorithm right now, but .. @vsoch can we provide a CLI to add/edits aliases, and make it so that these are retained, both for final use and eventually also for the algorithm to act better?

I don't think the algorithm can ever be perfect for everyone's needs - it's right now optimized to be more forgiving and err on the side of providing too many. If we are missing aliases (the list you gave) that usually is because we couldn't extract the container guts, and indeed a command line client to add them would be a great idea. How should that look? Would the user need to clone shpc-registry and then maybe run a script that is locally there to add an alias? E.g.,

```bash
$ git clone https://github.com/singularityhub/shpc-registry
$ cd shpc-registry
$ python add_alias quay.io/biocontainers/samtools samtools /opt/bin/samtools
```
Would that be simple enough?

**Comment by marcodelapierre** [comment]
Hi Vanessa, I did not explain myself clearly.

So version `0.0.57` is the reference "blessed" one,
I have carried out the check on the latest release of the registry, `2023-02`: https://github.com/singularityhub/shpc-registry/tree/2023-02

**Comment by marcodelapierre** [comment]
I love the CLI snippet!!

**Comment by marcodelapierre** [comment]
And I agree about your thoughts re: missing/extra aliases and the algorithm.
I think we might briefly mention the new CLI to add missing aliases in the paper, and that would be enough.

**Comment by vsoch** [comment]
>  I think we might briefly mention the new CLI to add missing aliases in the paper, and that would be enough.

It won't officially be a part of shpc, but just the repo here, since the user would need to clone it as a base requirement. Can you give me a few one off examples for aliases / containers to add and remove? I'll write it right now and PR!

**Comment by marcodelapierre** [comment]
`quay.io/biocontainers/spades` has both extras and missings when comparing shpc `0.0.57` and shpc-registry `2023-02`.
although for testing I reckon any would do.

when it's back into the `main`, I can run it through those packages myself!

**Comment by marcodelapierre** [comment]
so you would add `add_alias` and `remove_alias` interfaces?

**Comment by vsoch** [comment]
I made a small helper script in this repository here, see https://github.com/singularityhub/shpc-registry/pull/87.
